name: flutter_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3
  flutter_cache_manager: ^0.1.1
  serializable: any   # change by the latest dependency
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.3
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
     - assets/drawable/
     - assets/json_files/radicalMap
     - assets/json_files/strokeMap
     - assets/json_files/kdic2
